// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbiuryilcrwtkxygbnxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaXVyeWlsY3J3dGt4eWdibnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODgyNjcsImV4cCI6MjA2NTU2NDI2N30.lBrsrnPfq-VLZ7jeA6XH-JqTdWtZxynYcEtEbt5srkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);